#%RAML 0.8
title: Activity Custom Variables Services
version: 1
baseUri: http://localhost:8080/registry/account_manager/{module_version}/accounts/{account_key}/customVariables
documentation:
 - title: Activity Custom Variables services
   content: |
    Activity custom variables service deals with operations related to activity/account level custom variables, like list based on the privilege level user.
    
    Following operation can be done on the activity service.
    
    **List ( Listing down all the custom variables based on the scope provided by the user)**
