#%RAML 0.8
title: Model Instance Activation Service
version: V1
#baseUri: http://ServerName:ServerPort/registry/{module_name}/{module_version}
baseUri: http://localhost:8080/registry/model_upload/{module_version}/accounts/{account_key}/models/{model_key}/instances/{modelInstanceVersion}
/ModelInstanceActivation:
  description: This call activates the specified model instance and deactivates all other instances. Only one model instance can be active at the same time. When activating a model instance the API ensures that all other model instances are automatically deactivated. When an inactive model changes to the active state it becomes immutable except for the threshold. Further changes require a new model instance. There is no need for deactivating model instances. Activating an already active instance is not considered an error.
  
  post:
      description: POST request with **activate** action, requires UPDATE privilege.
      queryParameters: 
        token: 
          description: The token that was given in response to authentication request. It consists of 32 alphanumeric characters.
          required: true
        account_key:
          description: The account_key is the id of account.
          required: true
          type: integer
        Model_key:
          description: The model_key is the id of model.
          required: true
      body:
       application/json:
        example: |
           curl -v -k -L -X POST -H "Accept: application/json" -D -H "http://localhost:8080/modules/model_upload/1.0.30/accounts/1/models/a8307628-8648-446d-9342-66f626272d38/instances/1?token=3e505ed0-026e-4f8c-a1d8-862f72cb6192&action=activate"
      responses:
        201:               
          description: Created Successfully
        401:
          description: Unauthorized request
        404:
          description: Resource not found
           
  