#%RAML 0.8
title: Modeling Services
version: V1
#baseUri: http://ServerName:ServerPort/registry/{module_name}/{module_version}
baseUri: http://localhost:8080/registry/model_upload/{module_version}/accounts/{account_key}/models/{model_key}
documentation:
 - title: Modeling Services Introduction
   content: |
     Modeling is the process of creating a data model for an information system by applying formal data modeling techniques.
     
     Modeling is a process used to define and analyze data requirements needed to support the business processes within the scope of corresponding information systems in organizations.
      
      Modeling consists of 5 Services.
        
        **1) Modeling Services**
        
        **2) Model Instance Services**
        
        **3) Automatic Model Generation Service**
        
        **4) Bulk Scoring Service**
        
        **5) Iab's Services**
        