#%RAML 0.8
title: Advertiser Services
version: 1
baseUri: http://localhost:8080/registry/account_manager/{module_version}/accounts/{account_key}/advertisers
documentation:
 - title: Advertiser services
   content: |
    Advertiser service deals with operations related to advertiser, like add/update/delete/get/list based on the privilege level user.
      Following operation can be done on the account service.
        
      **List ( Listing down all the advertiser associated with the user)**
        
      **Get (To list down a particular advertiser by passing the account key)**
        
      **Add (Using this operation user can add a new advertiser to the system)**
        
      **Update (Using this operation user can update a particular advertiser)**
        
      **Delete (Using this operation user can delete a particular advertiser)** 
        
      **Execute (Using this operation use can activate/deactivate the advertiser)**
