#%RAML 0.8
title: Advertiser Activate/Inactivate Service
version: V1
#baseUri: http://ServerName:ServerPort/registry/{module_name}/{module_version}
baseUri: http://localhost:8080/registry/account_manager/{module_version}/accounts/{account_key}/advertisers/{advertiser_key}?token=token&action=activate
/AdvertiserActivationOrInactication:
  description: This service will be used to make a particular advertiser activate (enable) or inactivate (disable) in the turbine system.
  post:
      description: POST request with **activate** action or **inactivate** action, requires UPDATE privilege
      queryParameters: 
        token: 
          description: The token that was given in response to authentication request. It consists of 32 alphanumeric characters.
          required: true
        account_key: 
          description: The account_key is the id of account.
          required: true
          type: integer
      body:
       application/json:
        example: |
          Activate:
          
          curl  -X POST -H "Accept: application/json" "http://127.0.0.1:8080/modules/account_manager/1.0.0/accounts/303/advertisers/102?token=9dd88e89-8071-41a7-8fad-3b00f57a96a0&action=activate"
          
          Inactivate:
            
           curl  -X POST -H "Accept: application/json" "http://127.0.0.1:8080/modules/account_manager/1.0.0/accounts/303/advertisers/102?token=9dd88e89-8071-41a7-8fad-3b00f57a96a0&action=deactivate"
            
      responses:
        201:               
          description: Created Successfully
        401:
          description: Unauthorized request
        404:
          description: Resource not found
           