#%RAML 0.8
title: Advertiser Add Service
version: V1
#baseUri: http://ServerName:ServerPort/registry/{module_name}/{module_version}
baseUri: http://localhost:8080/registry/account_manager/{module_version}/accounts/{account_key}/advertisers
/Add:
  description: This section deals about the example to add a new advertiser to the turbine system.   
  post:
      description: POST request, requires ADD privilege. advertiser_json.json file used to create an advertiser is shown in the request example.
      queryParameters: 
        token: 
          description: The token that was given in response to authentication request. It consists of 32 alphanumeric characters.
          required: true
        name:
          description: The name of the advertiser mentioned in advertiser_json.json file while creating the advertiser.
          required: true
        notes:
          description: The description about the advertiser can be given in notes.
          required: false
        externalAdvertiserKey:
          description: This is an external key for the advertiser.
          required: true
          type: integer
      body:
       application/json:
        example: |
           curl  -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d @advertiser_json.txt "http://127.0.0.1:8080/modules/account_manager/1.0.0/accounts/5/advertisers?token=12472945-d02d-4804-bff5-67c2b597a998"
           
            advertiser_json.txt
              
             {
            "notes": "test test_",
            "name": "test_advertiser",
            "agencyKey": "2",
            "externalAdvertiserKey": 11211
            }
            
      responses:
        201:               
          description: Created Successfully
        401:
          description: Unauthorized request
        404:
          description: Resource not found
           
