#%RAML 0.8
title: Account Services
version: 1
baseUri: http://localhost:8080/registry/account_manager/{module_version}/accounts
documentation:
 - title: Account services
   content: |
     Account service deals with operations related to account, like add/update/delete/get/list based on the privilege level user.

      Following operation can be done on the account service.
      
       **List ( Listing down all the account associated with the user)**
       
       **Get (To list down a particular account by passing the account key)**
       
       **Add (Using this operation user can add a new account to the system)**
       
       **Update (Using this operation user can update a particular account)**
       
       **Delete (Using this operation user can delete a particular account)**
       
       **Execute (Using this operation use can activate/deactivate the account)**
