#%RAML 0.8
title: Activity Services
version: 1
baseUri: http://localhost:8080/registry/account_manager/{module_version}/accounts/{account_key}/activities
documentation:
 - title: Activity services
   content: |
    Activity service deals with operations related to activity, like add/update/delete/get/list based on the privilege level user.
    
    Following operation can be done on the activity service.
    
    **List ( Listing down all the activity associated with the user)**
    
    **Get (To list down a particular activity by passing the activity key)**
    
    **Add (Using this operation user can add a new activity to the system)**
    
    **Update (Using this operation user can update a particular activity)**
    
    **Delete (Using this operation user can delete a particular activity)**

