#%RAML 0.8
title: Iab's Services
version: V1
#baseUri: http://ServerName:ServerPort/registry/{module_name}/{module_version}
baseUri: http://localhost:8080/registry/model_upload/{module_version}/iabs?token=token
documentation:
 - title: Iab's Services
   content: |
    IAB(Interactive Advertising Bureau) provides services which includes a set of standard-size banner ads for World Wide Web pages. It provides services to corporations engaged in selling, measuring, monitoring, or producing advertising on the Internet. IAB categories are not account-specific. Iab service deals with operations related to Iab, like get/list based on the privilege level user.
    
    **List ( Listing down all the Iab associated with the user)**    
    
    **Get (To list down a particular Iab by passing the model key)**    