#%RAML 0.8
title: Account Manager Services
version: 1
baseUri: http://localhost:8080/registry/account_manager/{module_version}
documentation:
 - title: Account Manager Services
   content: |
     Account Manager Services allows the User to find the details of an account, advertiser, campaign and user.
     An account provides details of advertiser and campaign.