#%RAML 0.8
title: User Preference Services
version: 1
baseUri: http://localhost:8080/registry/account_manager/{module_version}/users/{user_id}/userPrefs
documentation:
 - title: User Preference services
   content: |
    User Preference service deals with operations related to user preferences, like add/update/delete/get/list based on the privilege level user.
      
    Following operation can be done on the campaign service.
        
      Following operation can be done on the user preference service.
      
      **List ( Listing down all the user preferences associated with the user)**
      
      **Get (To list down a particular user preference by passing the user preference key)**
      
      **Add (Using this operation user can add a new  preference to the system)**
      
      **Update (Using this operation user can update a particular user preference)**
      
      **Delete (Using this operation user can delete a particular user preference)**
