#%RAML 0.8
title: Campaign Delete Service
version: V1
#baseUri: http://ServerName:ServerPort/registry/{module_name}/{module_version}
baseUri: http://localhost:8080/registry/account_manager/{module_version}/accounts/{account_key}/advertisers/{advertiser_key}/campaigns/{campaign_key}
/Delete:
  description: This section will deals about how to delete a campaign of the turbine system. An inactive campaign can be deleted. An active campaign cannot be deleted.
  
  delete:
      description: DELETE request, requires DELETE privilege.
      queryParameters: 
        token: 
          description: The token that was given in response to authentication request. It consists of 32 alphanumeric characters.
          required: true
        account_key:
          description: The account_key is the id of account.
          required: true
          type: integer
        campaign_key:
          description: The campaign_key is the id of campaign.
          required: true
          type: integer
      body:
       application/json:
        example: |
          curl  -X DELETE -H "Accept: application/json" "http://127.0.0.1:8080/modules/account_manager/1.0.0/accounts/303/campaigns/102?token=9dd88e89-8071-41a7-8fad-3b00f57a96a0"
      responses:
        200:
          description: OK - The request has succeeded
        401:
          description: Unauthorized request
        404:
          description: Resource not found 
  
 
  
