#%RAML 0.8
title: User Services
version: 1
baseUri: http://localhost:8080/registry/account_manager/{module_version}/users
documentation:
 - title: User services
   content: |
    User service deals with operations related to user, like add/update/delete/get/list based on the privilege level user.
      
      Following operation can be done on the User service.
        
      **List ( Listing down all the User associated with the user)**
      
      **Get (To list down a particular User by passing the account key)**
      
      **Add (Using this operation user can add a new User to the system)**
      
      **Update (Using this operation user can update a particular User)**
      
      **Delete (Using this operation user can delete a particular User)**
      
      **Execute (Using this operation use can activate/deactivate the user)**
