#%RAML 0.8
title: User Change Password Service
version: V1
#baseUri: http://ServerName:ServerPort/registry/{module_name}/{module_version}
baseUri: http://localhost:8080/registry/account_manager/{module_version}/userUtility/{userkey}
/ChangePassword:
  description: This section will deals about how to a change user password of the turbine system
  put:
      description: PUT request, requires UPDATE privilege. change_password.json file used for changing password of the user is shown in the request example.
      queryParameters: 
        token: 
          description: The token that was given in response to authentication request. It consists of 32 alphanumeric characters.
          required: true
        user_key:
          description: The user_key is the id of user.
          required: true
          type: integer
      body:       
        application/json:
         example: |
            curl  -X PUT -H "Accept: application/json" -H "Content-Type: application/json" -d @user_json.txt "http://127.0.0.1:8080/modules/account_manager/1.0.0/ userUtility/13?token=12472945-d02d-4804-bff5-67c2b597a998" 
            
              user_json.txt
              
             {
              "password":"password",
                "newPassword":"password"
             }
    
           
      responses:
        200:
          body:
            application/json:
          description: OK - The request has succeeded
        401:
          description: Unauthorized request
        404: 
          description: Resource not found
  
