#%RAML 0.8
title: Query Manager Services
version: V1
#baseUri: http://ServerName:ServerPort/registry/{module_name}/{module_version}
baseUri: http://localhost:8080/registry/reporting/{module_version}/accounts
documentation:
 - title: Query Manager Services
   content: |
    Query Manager**'**s Services deal with operations related to get the reports based on generic query or/and special named queries to retrieve reports based on the privilege level user.
     
     Following operation can be done on the Query Manager Service.
    
      **List (To get a list of named queries)**
      
      **Execute ( To get a report based on a generic query)**

