#%RAML 0.8
title: Event Services
version: 1
baseUri: http://localhost:8080/registry/account_manager/{module_version}/accounts/{account_key}/campaigns/{campaign_key}/events
documentation:
 - title: Event services
   content: |
     Event service deals with operations related to Events, like add/update/delete/get/list based on the privilege level user.
       
      Following operation can be done on the event service.
      
      **List ( Listing down all the event associated with the user)**
      
      **Get (To list down a particular event by passing the event key)**
      
      **Add (Using this operation user can add a new event to the system)**
      
      **Update (Using this operation user can update a particular event)**
      
      **Delete (Using this operation user can delete a particular event) **
