#%RAML 0.8
title: Authentication Services
version: 1
baseUri: http://localhost:8080/registry/model_upload/{module_version}
documentation:
 - title: Authentication Services
   content: |
     It consists for Authentication Service and Logout Service
     
     The access token is acquired with a REST call to the module registry.
